version: '3'

services:
    app_backend:
      build:
        context: .
        dockerfile: Dockerfile 
      restart: always
      container_name: app_backend
      image: app_backend
      environment:
        port: 8000
        dburl: 'mongodb://localhost:27017/'
      expose:
        - "8000"
      ports:
        - '8000:8000'
      command: ["npm","start"]
      depends_on: 
        - mongo
    
    mongo: 
      image: "mongo:5.0.4"
      container_name: "mongo_db"
      ports:
        - "27017:27017"